name: Basic CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test pipeline
        run: echo "Pipeline works"
