name: CI Develop

on:
  push:
    branches:
      - 'develop/**'

jobs:
  pipeline:
    runs-on: [self-hosted, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run basic command
        run: echo "Pipeline is running successfully on develop!"

      - name: Show Docker version
        run: docker --version

      - name: Generate PDF documentation
        run: docker run --rm -u "$(id -u):$(id -g)" -v "$PWD":/data pandoc/extra documentation.md -o documentation.pdf
        working-directory: docs

      - name: Check output
        run: ls docs/
