name: CI Develop

on:
  push:
    branches:
      - 'develop/**'

jobs:
  pipeline:
    runs-on: [self-hosted, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run basic command
        run: echo "Pipeline is running successfully on develop!"

      - name: Show Docker version
        run: docker --version

      - name: Run Unit Tests
        run: docker run --rm -u "$(id -u):$(id -g)" -v "$PWD":/home/gradle/project -w /home/gradle/project gradle:8.14-jdk17 gradle test

      - name: Generate PDF documentation
        run: docker run --rm -u "$(id -u):$(id -g)" -v "$PWD":/data pandoc/extra documentation.md -o documentation.pdf
        working-directory: docs

      - name: Check output
        run: ls docs/

      - name: SonarQube Analysis (CLI)
        env:
          SQTOKEN: ${{ secrets.SQTOKEN }} 
          SQSERVER: "https://sonarcloud.io" 
          SCANNEROPTS: >-
            -Dsonar.projectKey=spexample
            -Dsonar.sources=src/main
            -Dsonar.java.libraries=build/libs
            -Dsonar.java.binaries=build/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
            -Dsonar.junit.reportsPath=build/test-results
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="${SQSERVER}" \
            -e SONAR_TOKEN="${SQTOKEN}" \
            -e SONAR_SCANNER_OPTS="${SCANNEROPTS}" \
            -v "${PWD}:/usr/src" \
            sonarsource/sonar-scanner-cli
