name: CI Release

on:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: [self-hosted, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t demo .

      - name: Tag image for registry
        run: docker image tag demo 10.0.40.169:5000/team6/demo:latest

      - name: Push image to registry
        run: docker image push 10.0.40.169:5000/team6/demo:latest

  deploy:
      runs-on: [self-hosted, deploy]
      needs: build
      steps:
        - name: Pull image from registry
          run: docker image pull 10.0.40.169:5000/team6/demo:latest

        - name: Remove old container if exists
          run: docker rm -f demo || true

        - name: Run application
          run: docker run -d -p 8086:8080 --name demo 10.0.40.169:5000/team6/demo:latest